name: Init Flutter (create project + debug APK)

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Create Flutter project if not exists
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create durt_app .
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
